Try to fix bridge issue
Error: ERROR: Error response from daemon: failed to set up container networking: failed to add interface veth67c35fa to sandbox: check bridge port state: bridge port not forwarding after 200ms

we already run in container (dind) so it should be ok

Signed-off-by: Dimitris Karakasilis <dimitris@karakasilis.me>